### ISSUE TITLE
Issue with showing certain images

### ISSUE THREAD

**Issue by Zero3K** [DiscordMessenger/dm#37]
![image](https://github.com/DiscordMessenger/dm/assets/6194332/a954a7da-bbe0-47ea-9ae3-c9300be57f25)

**Comment by Zero3K** [comment]
Is there any way I can help debug this issue?

**Comment by Zero3K** [comment]
It is also happening under Windows 7.

**Comment by Zero3K** [comment]
I wonder if -1 is a CORS issue or if it should just be interpreted as SUCCESS.

**Comment by iProgramMC** [comment]
It says "SSL connection failed" so definitely no success here.

**Comment by Zero3K** [comment]
You're right.

**Comment by Zero3K** [comment]
Maybe the image is being requested improperly.

**Comment by iProgramMC** [comment]
That url looks fine to me.

**Comment by Zero3K** [comment]
I mean, the program is trying to request it in an unexpected way.

**Comment by Zero3K** [comment]
Would Fiddler Classic help debug the issue?

**Comment by Zero3K** [comment]
I tried using it but it doesn't show the requests done by Discord Messenger since it isn't using Fiddler Classic's proxy function. Adding the ability for it to connect to Discord via a proxy server would let me use Fiddler Classic to debug this issue.

**Comment by iProgramMC** [comment]
You can do that.

**Comment by Zero3K** [comment]
How? I am not a programmer.

**Comment by Zero3K** [comment]
Its a proxy, not a Discord Server.

**Comment by iProgramMC** [comment]
You can fire HTTP requests to your Fiddler instance, correct? Therefore its IP address works in the API URL field.

**Comment by iProgramMC** [comment]
You set up your proxy to forward HTTP requests it receives to Discord's API.  D'oh!

**Comment by iProgramMC** [comment]
Well, and then you make DM connect to your proxy.

**Comment by Zero3K** [comment]
It doesn't work.

**Comment by Zero3K** [comment]
I tried installing WireShark to debug the issue. With it running and capturing only TCP port 443 traffic, the error doesn't show up. I am attaching both the log and the ssl.log as a ZIP archive. You can use it to decrypt the traffic by doing the second part shown in https://www.comparitech.com/net-admin/decrypt-ssl-with-wireshark/.

[Discord  Messenger WireShark Log.zip](https://github.com/DiscordMessenger/dm/files/15310988/Discord.Messenger.WireShark.Log.zip)

**Comment by iProgramMC** [comment]
I suggest you don't publish raw traffic dumps as they contain your discord token.

**Comment by Zero3K** [comment]
Then how can I help fix the issue?

**Comment by Zero3K** [comment]
So, I think the only way to get it fixed is for you to add system proxy support or logging of HTTPS requests to a file to DM so I can use Fiddler Classic to look at the request that is giving an error or give you the log so you can look for the cause and fix it.

**Comment by Zero3K** [comment]
> > I think it might be a WCF issue (I have a router that has Web Content filtering, which allows me to block ads, etc.).
> 
> You might want to whitelist cdn.discordapp.com then.

I am able to view the image associated with the URL in a browser though.

**Comment by Zero3K** [comment]
This is weird, its not happening even though I re-enabled the WCF rule in my router.

**Comment by Zero3K** [comment]
And now it is happening again.

**Comment by iProgramMC** [comment]
Could be.  Did you check the task manager's GDI object column? You can select columns shown in the "details" tab of task manager by right clicking the column header and selecting "Select columns".
![image](https://github.com/DiscordMessenger/dm/assets/17717494/c7a260f2-0835-487e-92c3-564285ed74e8)
![image](https://github.com/DiscordMessenger/dm/assets/17717494/0b911ea0-9785-44cd-aaf5-5ec910c90aef)

**Comment by Zero3K** [comment]
I am using Process Hacker 2. It's GDI handles instead of GDI objects in that program.

**Comment by Zero3K** [comment]
I wonder if it is getting a 302 code instead of a 200 code.

**Comment by iProgramMC** [comment]
It's... not getting anything because it can't connect in the first place. "-1" means there was no reply from the server.

**Comment by Zero3K** [comment]
I thought it meant a timeout or something.

**Comment by Zero3K** [comment]
Please add the ability for it to produce a request log so I can help debug this issue.

**Comment by iProgramMC** [comment]
I'm totally unsure how I can debug it, much less you.  I really don't know, you probably have spotty internet or something.  I'm going to close the issue because it doesn't seem like we can figure it out anytime soon.

**Comment by Zero3K** [comment]
I know how to debug it. I just need it to support system proxy settings so I can use Fiddler Classic to see what it shows when the error occurs.

**Comment by Zero3K** [comment]
![image](https://github.com/DiscordMessenger/dm/assets/6194332/c19ccf1e-950c-4eff-b2ae-5d393efe4354)

**Comment by iProgramMC** [comment]
Here's a breakdown, as I was able to understand:
```
error:C102C723:system library::reason(1090701091)   -> 0x4102C723
error:4102C723:lib(130)::reason(182051)             -> 0x0002C723
error:0002C723:lib(0)::reason(182051)               -> 0x0002C723 (LOOP)
```

It might be throwing error number 130 in a system library, which on Windows is supposedly EOPNOTSUPP.  Something isn't supported somehow.

**Comment by Zero3K** [comment]
![image](https://github.com/DiscordMessenger/dm/assets/6194332/2b47d7b2-6997-4f62-b0c1-e0a169c230cb)

**Comment by Zero3K** [comment]
![image](https://github.com/DiscordMessenger/dm/assets/6194332/1a72c680-51fd-452e-ad53-1d5ad8819702)

**Comment by Zero3K** [comment]
I wonder if it is possible to switch to a different SSL library (such as mbedTLS) since OpenSSL is giving a bunch of error codes.

**Comment by iProgramMC** [comment]
It is possible. Someone has done it before. You will need to remove an unused component from the app because it is written purely with OpenSSL 3.0 APIs, but it does work. Someone tried it with either boringSSL or wolfSSL, can't remember which. It just needs to be OpenSSL 1.X compatible.

**Comment by Zero3K** [comment]
It won't be done by me.

**Comment by Zero3K** [comment]
What is the point of the latest commit?

**Comment by iProgramMC** [comment]
Irrelevant to the issue at hand, but this fixes a bug that ended up causing MinGW builds of Discord Messenger to always report security errors.

**Comment by Zero3K** [comment]
Okay. Maybe you could try switching to a different SSL library or just wait for someone else to try. Because its looking like there's a bug in the version of OpenSSL that you are using.

**Comment by Zero3K** [comment]
![image](https://github.com/DiscordMessenger/dm/assets/6194332/ce2a9ce2-73c2-407d-8034-5d9d2a4ee306)

That is the only error code that I am getting when using the build GitHub Actions made from the latest commit.

**Comment by Zero3K** [comment]
Along with some errors not giving the SSL error code (but I think that code is the same as what is pictured).

**Comment by Zero3K** [comment]
Is that error fixable or not?

**Comment by iProgramMC** [comment]
I have no idea.

**Comment by Zero3K** [comment]
"This error occurs when the SSL layer is unable to negotiate a secure connection. This can happen when, as you said, the certificate is expired."

**Comment by Zero3K** [comment]
Would more debug output in the error message help? Such as showing the certificate's info, if its being re-encrypted, if a certificate is missing.

**Comment by iProgramMC** [comment]
I don't even know where to begin, honestly.

**Comment by Zero3K** [comment]
Try adding system proxy support so I can use Fiddler Classic to see if it shows anything interesting.

**Comment by iProgramMC** [comment]
I have already gone over this. If Fiddler Classic sets up a server on port 443 (a proxy is made up of a server AND a client- the client connects to official Discord backend and the server is for this program to connect to) - just use https://127.0.0.1 for the API URL.

**Comment by Zero3K** [comment]
It's too difficult to get Fiddler Classic to forward requests to its port to Discord's CDN server.

**Comment by iProgramMC** [comment]
Then don't forward requests to Discord's CDN server. API and CDN are two different things, you need to forward the API.

**Comment by Zero3K** [comment]
It's not the API server that is having the issue. It's the CDN server that is having the issue displaying images.

**Comment by Zero3K** [comment]
And its also difficult to do the same for the API link.

**Comment by Zero3K** [comment]
How about trying a different SSL library since you won't add the ability for it to use the HTTPS proxy set by Internet Options?

**Comment by Zero3K** [comment]
How do you know that there are people that tried changing the SSL Library that is being used?

**Comment by iProgramMC** [comment]
I was informed personally by them.

**Comment by Zero3K** [comment]
> I was informed personally by them.

Did they have any luck?

**Comment by iProgramMC** [comment]
Yes, but they had to disable the unused QR code dialog feature to make it work.  AFAIK, wolfSSL and BoringSSL should work.

**Comment by Zero3K** [comment]
I am interested in trying a build of Discord Messenger that uses either of them or mbedTLS.

**Comment by Zero3K** [comment]
I guess you won't try that.

**Comment by Zero3K** [comment]
Hopefully someone else can do that and make a PR.

**Comment by Zero3K** [comment]
Still nothing that you want to try?

**Comment by iProgramMC** [comment]
Nope. Please do not continue sending messages to this issue.

**Comment by iProgramMC** [comment]
@Zero3K I believe you may want to try the latest build. I've modified some settings in the HTTP client. I was able to mitigate "SSL connection failed" errors on Windows 2000 by reducing the thread count used by the HTTP client. Let me know if you still get these issues.

**Comment by Zero3K** [comment]
It's weird that its now not happening all of the time. I wonder if it is possible to have it keep trying to get the image until it gets a 404 or similar error.

**Comment by iProgramMC** [comment]
It's good.

It might be possible but I'm kind of lazy to tackle that. I'll tackle it if it becomes an actual problem.

**Comment by Zero3K** [comment]
I am using a DrayTek Vigor2927 router with its WCF function being used.

**Comment by Zero3K** [comment]
I don't know how to make it reproduceable for you.

**Comment by Zero3K** [comment]
I wonder why it only happens when viewing images, etc. in the channel.

**Comment by iProgramMC** [comment]
Make sure you are using V1.04 or the latest artifact - in the meantime I have fixed a similar "SSL connection failed" issues on Windows 2000.

**Comment by Zero3K** [comment]
I am using the latest artifact. The SSL connection failed (with an HTTP error code of -1 and SSL error code of 0x5) errors are still happening. Is there any difference in regards to connecting to the server between the code used for the message viewer/etc. when compared to the code used for the viewer of images when clicking on them?

**Comment by iProgramMC** [comment]
No. Now, I'm pretty sure it's your internet connection. Just to confirm though, could you download and run the latest artifact when it's done building?

Anyway, yes there is a difference, but it's mostly just fetching the image with a particular size.

**Comment by Zero3K** [comment]
![image](https://github.com/DiscordMessenger/dm/assets/6194332/37b46d69-63c7-4098-a1ea-6e38b6e8a8f2)

https://github.com/openssl/openssl/issues/18785

**Comment by iProgramMC** [comment]
0x80000000 is not a valid error code. Actually it's `0x80000000 | 0x00000000` which is actually what I was looking for. It looks like `ERR_get_error()` is returning zero after `SSL_get_error()` returns `SSL_ERROR_SYSCALL`.

Here's the code the generates this code:
```cpp
template <typename U>
bool ssl_connect_or_accept_nonblocking(socket_t sock, SSL *ssl,
									   U ssl_connect_or_accept,
									   time_t timeout_sec,
									   time_t timeout_usec) {
  int res = 0;
  while ((res = ssl_connect_or_accept(ssl)) != 1) {
	auto err = SSL_get_error(ssl, res);
	switch (err) {
	case SSL_ERROR_WANT_READ:
	  if (select_read(sock, timeout_sec, timeout_usec) > 0) { continue; }
	  break;
	case SSL_ERROR_WANT_WRITE:
	  if (select_write(sock, timeout_sec, timeout_usec) > 0) { continue; }
	  break;
	default: break;
	}
	// To debug an issue, setting a global:
	g_latestSSLError = err;
	if (err == SSL_ERROR_SYSCALL) {
	  g_latestSSLError = 0x80000000 | ERR_get_error(); // hope that OpenSSL doesn't set that 31st bit
	}
	return false;
  }
  return true;
}
```

**Comment by iProgramMC** [comment]
Try with this next artifact. It's going to show a more detailed log. Press CTRL-C on every message box that shows up and paste it here. Yes, you can do that, here's what it looks like:
```
---------------------------

---------------------------
Yo, you're seeing the hacky handler for SSL_ERROR_SYSCALL. You're about to see the result of ERR_get_error().
---------------------------
OK   
---------------------------
```

**Comment by iProgramMC** [comment]
I screwed it up even worse, try this artifact instead.

**Comment by Zero3K** [comment]
![image](https://github.com/DiscordMessenger/dm/assets/6194332/494de73f-688c-40a2-bf90-3c286a007156)
![image](https://github.com/DiscordMessenger/dm/assets/6194332/4debf5de-a6ef-44c7-84ca-31ed8dc78b3a)
![image](https://github.com/DiscordMessenger/dm/assets/6194332/2ab8658e-6ea6-4a49-a593-965b2b7e3699)
![image](https://github.com/DiscordMessenger/dm/assets/6194332/2e7baace-726e-46a2-9139-f7587b9615fa)

**Comment by Zero3K** [comment]
Maybe https://stackoverflow.com/a/46603531 will help.

**Comment by iProgramMC** [comment]
Given that the error occurs in `ssl_connect_or_accept_nonblocking`, I don't think it manged to actually read anything. But, I've increased the recv buffer size, so try again.

**Comment by Zero3K** [comment]
That didn't work.

**Comment by iProgramMC** [comment]
Same?

**Comment by Zero3K** [comment]
Yes.

**Comment by Zero3K** [comment]
https://stackoverflow.com/questions/64041863/how-to-use-ssl-read-and-ssl-accept-on-non-blocking
https://stackoverflow.com/questions/28508374/ssl-connect-for-non-blocking-socket
https://stackoverflow.com/questions/68387278/error-1-when-attempting-to-accept-a-non-blocking-openssl-socket-accepting-twic
https://stackoverflow.com/questions/38937900/c-openssl-fails-to-perform-handshake-when-accepting-in-non-blocking-mode-what

**Comment by Zero3K** [comment]
What is the latest commit for?

**Comment by iProgramMC** [comment]
It disables the use of I/O completion ports for Asio.  I/O Completion Port APIs are not implemented in Windows 9x, which I was trying to haggle to make work, but without luck.

**Comment by Zero3K** [comment]
Okay.

**Comment by Zero3K** [comment]
Are any of the links I recently posted helpful or not?

**Comment by iProgramMC** [comment]
I don't think so, sorry.

**Comment by Zero3K** [comment]
That's not good. Maybe just try implementing the retrying like I mentioned earlier.

**Comment by Zero3K** [comment]
Maybe adding a log file dump on a SSL error will help find the cause.

**Comment by iProgramMC** [comment]
a8a6d56 probably isn't going to do anything to solve this issue, but it does solve an architectural problem.

**Comment by Zero3K** [comment]
It fixed the issue.

**Comment by Zero3K** [comment]
How about marking this issue as solved by that commit?

**Comment by iProgramMC** [comment]
Whatever, it's been closed for a few weeks now.
