### ISSUE TITLE
Server emotes are not showing

### ISSUE THREAD

**Issue by Zero3K** [DiscordMessenger/dm#43]
For example, take a look at #hang_out in Background Noise (https://discord.com/invite/0v8a0me0lm28o7m1). Here's a screenshot of what is being shown instead:

![image](https://github.com/DiscordMessenger/dm/assets/6194332/e0c7ae71-427a-4447-8f2d-0a73e0bc2f7f)

**Comment by iProgramMC** [comment]
They... are not. This is because they aren't added yet. This is not an issue.

**Comment by Zero3K** [comment]
You didn't need to mark it as not planned. That makes it look like you're not going to add support for them.

**Comment by Zero3K** [comment]
Now I am seeing a Discord Icon in place of the actual emote.

**Comment by iProgramMC** [comment]
Ok, that's an oversight. For now try dragging the window off screen and back in view, this should refresh it

**Comment by iProgramMC** [comment]
This has been fixed. Unless the emoji can't be loaded it should work.

**Comment by Zero3K** [comment]
It is still happening for me (but this time scrolling past it and back to it gets it to show instead of the Discord icon).

**Comment by Zero3K** [comment]
Also:

![image](https://github.com/DiscordMessenger/dm/assets/6194332/6488f9e3-bf26-4404-9cac-1ada5fb9da49)

**Comment by iProgramMC** [comment]
Ok, I fixed that one.

**Comment by Zero3K** [comment]
![image](https://github.com/DiscordMessenger/dm/assets/6194332/34e3b77b-3735-4804-b95d-bed27ffbce29)

That is how that and the emoticon are supposed to look.

**Comment by iProgramMC** [comment]
Yup, it should have been fixed now. You can clear cache and they should show up.

**Comment by Zero3K** [comment]
Thanks. So, animated emoticons will come when there's MP4 support added?

**Comment by iProgramMC** [comment]
No and no. I don't think I will support animated images or video for now. You can download MP4s directly from the app, so at least you can play those using your favorite media player.

**Comment by Zero3K** [comment]
Okay. I will wait and see what happens later on.

**Comment by K4sum1** [comment]
I think this is still broken
![image](https://github.com/user-attachments/assets/0ab9274b-84fe-4c44-8ee4-eb520c333e44)

**Comment by Zero3K** [comment]
It doesn't support animated emoticons and images yet.

**Comment by K4sum1** [comment]
Should I make an issue for full emoji support? (emoji picker and animated emojis)

**Comment by iProgramMC** [comment]
For Unicode emojis, see #81.

You can create one for animated server emojis.  Note that even if I implement them, they will not be animated.

**Comment by K4sum1** [comment]
> Note that even if I implement them, they will not be animated.

Why? That literally just means I will never use this client unless someone forks and makes them animated. I might as well just not make the issue.

**Comment by Zero3K** [comment]
> > Note that even if I implement them, they will not be animated.
> 
> Why? That literally just means I will never use this client unless someone forks and makes them animated. I might as well just not make the issue.

https://github.com/DiscordMessenger/dm/issues/47

**Comment by K4sum1** [comment]
Why not just access them as a gif? The animated emojis are all .gif files.

**Comment by Zero3K** [comment]
> Why not just access them as a gif? The animated emojis are all .gif files.

I don't think they are.

**Comment by K4sum1** [comment]
Well, you could just point to the url, which is a gif.

**Comment by iProgramMC** [comment]
> Why? That literally just means I will never use this client unless someone forks and makes them animated. I might as well just not make the issue.

It requires complex support on my part because I have to write a GIF loader, and keep all the animations in sync.  It's actually quite a challenge to manage several animations running simultaneously.

If the lack of features is turning you off, I'm sorry to hear that, but it is what it is. Maybe Discord Messenger is not for you.

**Comment by iProgramMC** [comment]
> I don't think they are.

Indeed they are GIFs.

**Comment by K4sum1** [comment]
> If the lack of features is turning you off, I'm sorry to hear that, but it is what it is. Maybe Discord Messenger is not for you.

What I want is a good, not bloated local client. Just using Discord makes the CPU on my laptop shoot up to mid-high 80s. The closest thing is Ripcord, but that hasn't had any development in years and has it's own weird bugs that makes me unable to use it.

**Comment by Zero3K** [comment]
We just need someone to make a PR that implements animated GIF support.
